### ISSUE TITLE
Arista Networks logo should not be present in the adopters marquee

### ISSUE THREAD

**Issue by fessaries** [openebs/website#400]
Hi. Arista Networks was removed as an adopter here: https://github.com/openebs/openebs/commit/a095371bb7a01ad5b817122c27d02e1be978ee56

Can I kindly request that the Arista Networks logo be removed from the landing page of https://openebs.io/

**Comment by avishnu** [comment]
Noted.

**Comment by orville-wright** [comment]
Why did we make this change? @avishnu @niladrih ??

How can we verify that identity of @fessaries that they speak with some authority for ARISTA Networks?
I think this is a reasonable question to ask here... as anyone could ask to add/remove a logo from our website. - How do we validate the authenticity of this request?

**Comment by avishnu** [comment]
The request seems authentic. I'm closing this ticket, as the PR #432 to remove log has been merged.
